declare module "cloudflare:workers" {
  // Runtime bindings are generated by Cloudflare; the local shim stays open-ended.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  export const env: Record<string, any>;
}
