export const DEFAULT_LIMITS = {
  QUERIES_PER_RUN: 20,
  ITEMS_PER_SOURCE: { naver: 500, threads: 200, appstore: 300, hn: 100 },
  DISCOVERY_MODE_MAX: 300,
  LLM1_MAX_CALLS_PER_RUN: 60,
  LLM2_MAX_CALLS_PER_RUN: 40,
  VERIFY_MAX_PER_RUN: 20,
  LLM_MAX_RETRIES: 1,
  DAILY_COST_CEILING_USD: 3,
} as const;

export const HARD_LIMITS = {
  QUERIES_PER_RUN: 50,
  ITEMS_PER_SOURCE: 1200,
  DISCOVERY_MODE_MAX: 500,
  DAILY_COST_CEILING_USD: 10,
} as const;
