export const DEFAULT_LIMITS = {
  QUERIES_PER_RUN: 20,
  ITEMS_PER_SOURCE: { naver: 500, threads: 200, appstore: 300, hn: 100 },
  DISCOVERY_MODE_MAX: 300,
  LLM1_MAX_CALLS_PER_RUN: 60,
  LLM2_MAX_CALLS_PER_RUN: 40,
  VERIFY_MAX_PER_RUN: 20,
  LLM_MAX_RETRIES: 1,
  DAILY_COST_CEILING_USD: 3,
} as const;

export const MANUAL_RUN_LIMITS = {
  MAX_QUERIES: 5,
  ITEMS_PER_SOURCE: 50,
  MAX_SOURCES: 2,
  LLM1_MAX_CALLS: 20,
  LLM2_MAX_CALLS: 20,
  AUTO_VERIFY_TOP_N: 10,
} as const;

export const AUTO_RUN_LIMITS = {
  MAX_QUERIES: DEFAULT_LIMITS.QUERIES_PER_RUN,
  ITEMS_PER_SOURCE: DEFAULT_LIMITS.ITEMS_PER_SOURCE.naver,
  LLM1_MAX_CALLS: DEFAULT_LIMITS.LLM1_MAX_CALLS_PER_RUN,
  LLM2_MAX_CALLS: DEFAULT_LIMITS.LLM2_MAX_CALLS_PER_RUN,
  AUTO_VERIFY_TOP_N: DEFAULT_LIMITS.VERIFY_MAX_PER_RUN,
} as const;

export const RUN_TIME_BUDGET = {
  DEADLINE_MS: 250_000,
  PERSISTENCE_RESERVE_MS: 30_000,
} as const;

export function hasRunProcessingBudget(deadlineAt: number, now = Date.now()) {
  return now + RUN_TIME_BUDGET.PERSISTENCE_RESERVE_MS < deadlineAt;
}

export const HARD_LIMITS = {
  QUERIES_PER_RUN: 50,
  ITEMS_PER_SOURCE: 1200,
  DISCOVERY_MODE_MAX: 500,
  DAILY_COST_CEILING_USD: 10,
} as const;
